# Bài tập thực hành 


## LÀM QUEN VỚI PYTORCH

## Bài 1. Tạo Tensor cơ bản

**Yêu cầu:** Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

**Giải thích:**
- Sử dụng hàm `torch.tensor()` để tạo Tensor từ một list lồng nhau (2 hàng, 3 cột).
- Tham số `dtype=torch.int32` chỉ định kiểu dữ liệu là số nguyên 32-bit.
- Tensor tạo ra là một Tensor 2 chiều, tương tự ma trận toán học.


In [11]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)
print("Kích thước (shape):", a.shape)
print("Kiểu dữ liệu (dtype):", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước (shape): torch.Size([2, 3])
Kiểu dữ liệu (dtype): torch.int32


## Bài 2. Tạo các Tensor thường dùng

**Yêu cầu:** Tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1, ma trận đơn vị.
Nhận xét sự khác nhau giữa `torch.rand()` và `torch.randn()`.
Tạo thêm một Tensor 5×5 chứa toàn giá trị 10.

**Giải thích các hàm:**
- `torch.rand(3, 4)`: tạo Tensor kích thước 3×4 với các giá trị ngẫu nhiên lấy từ **phân phối đều (uniform)** trong khoảng [0, 1).
- `torch.randn(3, 4)`: tạo Tensor kích thước 3×4 với các giá trị ngẫu nhiên lấy từ **phân phối chuẩn (normal/Gaussian)**, trung bình = 0, độ lệch chuẩn = 1 → giá trị có thể âm hoặc lớn hơn 1.
- `torch.zeros(2, 3)`: tạo Tensor 2×3 toàn giá trị 0.
- `torch.ones(2, 3)`: tạo Tensor 2×3 toàn giá trị 1.
- `torch.eye(4)`: tạo ma trận đơn vị (identity matrix) kích thước 4×4 — đường chéo chính là 1, còn lại là 0.
- `torch.full((5, 5), 10)`: tạo Tensor 5×5 với mọi phần tử đều bằng 10 (dùng cho yêu cầu thêm).

In [12]:
import torch

a = torch.rand(3, 4)     # phân phối đều [0, 1)
b = torch.randn(3, 4)    # phân phối chuẩn (mean=0, std=1)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("a (rand) =\n", a)
print("b (randn) =\n", b)
print("c (zeros) =\n", c)
print("d (ones) =\n", d)
print("e (eye) =\n", e)

# Yêu cầu thêm: Tensor 5x5 toàn giá trị 10
f = torch.full((5, 5), 10)
print("f (full 10) =\n", f)


a (rand) =
 tensor([[0.1337, 0.1037, 0.1296, 0.8867],
        [0.4072, 0.8502, 0.2130, 0.2855],
        [0.0557, 0.5186, 0.5815, 0.1401]])
b (randn) =
 tensor([[-0.3694,  0.0351,  0.0076,  1.0202],
        [ 0.0467,  0.5697,  0.1815, -0.3056],
        [ 0.9987, -0.8705,  0.4328,  0.7048]])
c (zeros) =
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
d (ones) =
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
e (eye) =
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
f (full 10) =
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor

**Yêu cầu:** Sử dụng `shape`, `size()`, `ndim`, `dtype` để kiểm tra thuộc tính của Tensor.
Giải thích ý nghĩa của `torch.Size([2, 3, 4])`.

**Giải thích các thuộc tính:**
- `a.shape` / `a.size()`: trả về kích thước của Tensor theo từng chiều — hai cách gọi này tương đương nhau, chỉ khác cú pháp (`shape` là thuộc tính, `size()` là phương thức).
- `a.ndim`: số chiều (số trục) của Tensor.
- `a.dtype`: kiểu dữ liệu của các phần tử trong Tensor.
- `torch.zeros(2, 3, 4)` tạo một Tensor **3 chiều**, có thể hình dung như một "khối hộp" gồm 2 lớp ma trận, mỗi ma trận kích thước 3×4.

In [13]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)
print("Number of elements:", a.numel())

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32
Number of elements: 24


## Bài 4. Slicing và Indexing

**Yêu cầu:** Truy xuất một phần dữ liệu từ Tensor nhiều chiều.
Cho biết shape của `a[1]` và `a[1:, 2:4]`. Lấy hai phần tử cuối cùng trên chiều thứ ba.

**Giải thích:**
- `a` có kích thước `(3, 4, 5)` → gồm 3 "khối", mỗi khối là ma trận 4×5.
- `a[1]`: lấy khối thứ hai (chỉ số bắt đầu từ 0), kết quả là một ma trận 2 chiều.
- `a[1:, 2:4]`: 
  - `1:` trên chiều 0 → lấy từ khối 1 đến hết (bỏ khối 0).
  - `2:4` trên chiều 1 → lấy hàng 2 và hàng 3 (2 hàng) trong mỗi khối còn lại.
  - Chiều 2 (cột) giữ nguyên vì không chỉ định.
- Để lấy 2 phần tử cuối trên chiều thứ ba (chiều cuối, index 2), dùng slicing `[..., -2:]`, trong đó `...` giữ nguyên các chiều trước đó.

In [14]:
import torch

a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("Shape a:", a.shape)

print("\nTensor a[1]:")
print(a[1])
print("Shape a[1]:", a[1].shape)

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)

# Yêu cầu thêm: lấy 2 phần tử cuối trên chiều thứ ba (chiều cuối cùng)
print("\nHai phần tử cuối trên chiều thứ ba (a[..., -2:]):")
print(a[..., -2:])
print("Shape:", a[..., -2:].shape)

Original tensor:
tensor([[[ 1.4785,  0.6220, -0.1282, -1.3630, -0.6575],
         [-0.6687, -1.7627,  1.2312, -0.5098, -0.4146],
         [-1.2102,  1.6853, -0.8170,  1.0056,  1.3891],
         [ 0.6972,  1.9651, -2.2424,  1.0228,  2.0073]],

        [[-1.2223,  0.1302, -0.2789,  1.0469, -0.2909],
         [ 1.0239,  1.5103, -1.5967, -0.3525, -0.1281],
         [-0.1373, -0.3448,  0.1085, -0.9619, -0.0662],
         [ 0.9933,  1.2840, -0.5131,  1.8801, -0.7605]],

        [[ 1.4741, -0.0752, -1.4713, -0.5374, -0.8479],
         [-0.5287, -0.1205,  2.4808, -0.4232, -1.6249],
         [ 0.5374,  0.3978, -0.7801, -0.7622, -0.5260],
         [ 1.2862,  1.2646,  0.3820,  0.7819,  0.5293]]])
Shape a: torch.Size([3, 4, 5])

Tensor a[1]:
tensor([[-1.2223,  0.1302, -0.2789,  1.0469, -0.2909],
        [ 1.0239,  1.5103, -1.5967, -0.3525, -0.1281],
        [-0.1373, -0.3448,  0.1085, -0.9619, -0.0662],
        [ 0.9933,  1.2840, -0.5131,  1.8801, -0.7605]])
Shape a[1]: torch.Size([4, 5])

Tensor 

## Bài 5. Reshape và Flatten

**Yêu cầu:** Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.
Kiểm tra số phần tử trước/sau reshape. Thử reshape thành 2×6.

**Giải thích:**
- `a.ravel()`: "làm phẳng" Tensor thành một vector 1 chiều, giữ nguyên thứ tự phần tử (duyệt theo hàng).
- `a.reshape(3, 2, 2)`: thay đổi hình dạng Tensor thành 3 chiều, miễn là tổng số phần tử không đổi (3×2×2 = 12 = 3×4).
- Điều kiện bắt buộc khi reshape: **tích các chiều mới phải bằng tích các chiều cũ** (bằng đúng số phần tử `numel()`), nếu không sẽ báo lỗi.
- `a.reshape(2, 6)`: 2×6 = 12, hợp lệ vì bằng số phần tử ban đầu (3×4 = 12).

In [15]:
import torch

a = torch.randn(3, 4)
print("Original:")
print(a)
print("Số phần tử ban đầu (numel):", a.numel())

print("\nFlatten:")
print(a.ravel())
print("Số phần tử sau flatten:", a.ravel().numel())

print("\nReshape to 3 x 2 x 2:")
r1 = a.reshape(3, 2, 2)
print(r1)
print("Số phần tử sau reshape(3,2,2):", r1.numel())

# Yêu cầu thêm: reshape thành 2 x 6
print("\nReshape to 2 x 6:")
r2 = a.reshape(2, 6)
print(r2)
print("Số phần tử sau reshape(2,6):", r2.numel())

Original:
tensor([[-0.4018, -0.9784,  0.5054,  1.2719],
        [ 1.6677, -1.1669, -0.9531, -0.8214],
        [-0.1124, -1.1984, -0.7890,  0.8731]])
Số phần tử ban đầu (numel): 12

Flatten:
tensor([-0.4018, -0.9784,  0.5054,  1.2719,  1.6677, -1.1669, -0.9531, -0.8214,
        -0.1124, -1.1984, -0.7890,  0.8731])
Số phần tử sau flatten: 12

Reshape to 3 x 2 x 2:
tensor([[[-0.4018, -0.9784],
         [ 0.5054,  1.2719]],

        [[ 1.6677, -1.1669],
         [-0.9531, -0.8214]],

        [[-0.1124, -1.1984],
         [-0.7890,  0.8731]]])
Số phần tử sau reshape(3,2,2): 12

Reshape to 2 x 6:
tensor([[-0.4018, -0.9784,  0.5054,  1.2719,  1.6677, -1.1669],
        [-0.9531, -0.8214, -0.1124, -1.1984, -0.7890,  0.8731]])
Số phần tử sau reshape(2,6): 12


## Bài 6. Phép toán và nhân ma trận

**Yêu cầu:** Thực hiện phép toán phần tử và phép nhân ma trận bằng toán tử `@`.
Phân biệt `a * b` với `a @ b.T`. Cho biết shape của `a @ b.T`.

**Giải thích:**
- `a + b`, `a / b`, `a ** 2`, `a * b`: đây là các **phép toán theo từng phần tử (element-wise)** — yêu cầu hai Tensor phải cùng shape (hoặc broadcast được), kết quả cũng có shape giống hai Tensor gốc.
- `a @ b.T`: đây là **phép nhân ma trận (matrix multiplication)** theo quy tắc đại số tuyến tính, không phải nhân từng phần tử. `b.T` là chuyển vị của `b` để shape khớp cho phép nhân ma trận: `(2,3) @ (3,2) → (2,2)`.

In [16]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)

# Yêu cầu: phân biệt a * b với a @ b.T
print("\na * b (element-wise):")
print(a * b)
print("Shape a*b:", (a * b).shape)

print("\nMatrix multiplication a @ b.T:")
print(a @ b.T)
print("Shape a @ b.T:", (a @ b.T).shape)

a:
tensor([[ 1.1173,  0.8114, -0.8065],
        [-1.1364,  0.4964,  0.6909]])
b:
tensor([[-0.2096,  0.3348, -0.7446],
        [ 0.1952,  1.0318, -0.3394]])

a + b:
tensor([[ 0.9077,  1.1462, -1.5511],
        [-0.9412,  1.5282,  0.3515]])

a / b:
tensor([[-5.3303,  2.4237,  1.0832],
        [-5.8222,  0.4811, -2.0358]])

a^2:
tensor([[1.2484, 0.6584, 0.6505],
        [1.2915, 0.2464, 0.4774]])

a * b (element-wise):
tensor([[-0.2342,  0.2716,  0.6006],
        [-0.2218,  0.5122, -0.2345]])
Shape a*b: torch.Size([2, 3])

Matrix multiplication a @ b.T:
tensor([[ 0.6380,  1.3290],
        [-0.1101,  0.0559]])
Shape a @ b.T: torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor

**Yêu cầu:** Tính trung bình, độ lệch chuẩn, tổng tích lũy theo từng cột.
Thay `dim=0` bằng `dim=1` và nhận xét sự khác nhau.

**Giải thích:**
- `dim` chỉ định **chiều mà phép tính được thực hiện dọc theo** (chiều đó sẽ bị "thu gọn" lại sau khi tính, trừ `cumsum` giữ nguyên shape).
- Với Tensor 2 chiều `(hàng, cột)`:
  - `dim=0`: tính toán **dọc theo các hàng** → tức là gộp theo từng **cột** (mỗi cột cho ra 1 giá trị).
  - `dim=1`: tính toán **dọc theo các cột** → tức là gộp theo từng **hàng** (mỗi hàng cho ra 1 giá trị).
- `torch.cumsum(a, dim=...)`: tính tổng tích lũy (cộng dồn) theo chiều chỉ định, không làm giảm shape.

In [17]:
import torch

a = torch.randn(3, 4)
print(a)

print("\nMean dim=0:")
print(torch.mean(a, dim=0))
print("\nStandard deviation dim=0:")
print(torch.std(a, dim=0))
print("\nCumulative sum dim=0:")
print(torch.cumsum(a, dim=0))

# Yêu cầu: thay dim=0 bằng dim=1
print("\n=== dim=1 ===")
print("Mean dim=1:")
print(torch.mean(a, dim=1))
print("\nStandard deviation dim=1:")
print(torch.std(a, dim=1))
print("\nCumulative sum dim=1:")
print(torch.cumsum(a, dim=1))

tensor([[ 1.3309, -0.5684, -1.9975, -0.4983],
        [ 0.1665,  1.0499, -0.4776, -0.0570],
        [-0.3963,  0.2302, -1.4901,  0.7961]])

Mean dim=0:
tensor([ 0.3670,  0.2372, -1.3217,  0.0803])

Standard deviation dim=0:
tensor([0.8809, 0.8092, 0.7738, 0.6580])

Cumulative sum dim=0:
tensor([[ 1.3309, -0.5684, -1.9975, -0.4983],
        [ 1.4974,  0.4814, -2.4751, -0.5553],
        [ 1.1011,  0.7116, -3.9651,  0.2408]])

=== dim=1 ===
Mean dim=1:
tensor([-0.4333,  0.1704, -0.2150])

Standard deviation dim=1:
tensor([1.3640, 0.6442, 0.9797])

Cumulative sum dim=1:
tensor([[ 1.3309,  0.7625, -1.2350, -1.7333],
        [ 0.1665,  1.2163,  0.7388,  0.6818],
        [-0.3963, -0.1661, -1.6562, -0.8601]])


## Bài 8. Autograd cơ bản

**Yêu cầu:** Tạo biến `requires_grad=True`, dùng `backward()` để tính đạo hàm tự động.
Tính thủ công đạo hàm của y = x² tại x = 3.6 và so sánh với `x.grad`.
Đổi hàm thành y = 3x² + 2x + 1 và kiểm tra gradient.

**Giải thích:**
- `requires_grad=True`: yêu cầu PyTorch theo dõi (track) mọi phép toán trên `x` để có thể tính đạo hàm sau này (xây dựng đồ thị tính toán - computation graph).
- `y.backward()`: thực hiện lan truyền ngược (backpropagation), tự động tính đạo hàm `dy/dx` và lưu vào `x.grad`.
- `grad_fn=<MulBackward0>`: cho biết `y` được tạo ra từ phép nhân (`x * x`), PyTorch dùng thông tin này để biết cách tính đạo hàm ngược.
- Đạo hàm thủ công của `y = x²` là `dy/dx = 2x`.
- Đạo hàm thủ công của `y = 3x² + 2x + 1` là `dy/dx = 6x + 2`.

In [18]:
import torch

x = torch.tensor(3.6, requires_grad=True)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

# Yêu cầu thêm: đổi hàm thành y = 3x^2 + 2x + 1
print("\n=== Đổi hàm mới: y = 3x^2 + 2x + 1 ===")
x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * x2 ** 2 + 2 * x2 + 1
y2.backward()
print("x2 =", x2)
print("y2 =", y2)
print("x2.grad =", x2.grad)
print("Đạo hàm thủ công 6x+2 =", 6 * 3.6 + 2)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)

=== Đổi hàm mới: y = 3x^2 + 2x + 1 ===
x2 = tensor(3.6000, requires_grad=True)
y2 = tensor(47.0800, grad_fn=<AddBackward0>)
x2.grad = tensor(23.6000)
Đạo hàm thủ công 6x+2 = 23.6


## Bài 9. Gradient Descent tìm hệ số đa thức

**Yêu cầu:** Sinh dữ liệu từ đa thức y = x² + 2x + 3, dùng NAdam và autograd để tìm lại 3 hệ số.
So sánh hệ số học được với [1, 2, 3]. Giải thích vai trò của `optimizer.zero_grad()`, `mse.backward()`, `optimizer.step()`.

**Giải thích:**
- `np.poly1d([1, 2, 3])`: tạo đa thức `1·x² + 2·x + 3`, dùng để sinh dữ liệu "nhãn" `Y` từ `X` ngẫu nhiên.
- `XX = [X², X, 1]`: xây ma trận đặc trưng để bài toán trở thành **hồi quy tuyến tính** theo 3 hệ số `w = [w0, w1, w2]`, vì `y = w0·x² + w1·x + w2 = XX @ w`.
- `w = torch.randn(3, 1, requires_grad=True)`: khởi tạo 3 hệ số ngẫu nhiên, cần tính gradient vì đây là tham số cần học.
- `torch.optim.NAdam([w], lr=0.01)`: bộ tối ưu NAdam (biến thể của Adam có thêm Nesterov momentum), cập nhật `w` để giảm hàm mất mát (MSE).
- Vòng lặp huấn luyện (1000 epoch) thực hiện lặp lại 3 bước cốt lõi: xóa gradient cũ → tính lại gradient mới qua backward → cập nhật trọng số.

In [19]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    if (epoch + 1) % 200 == 0:
        print(f"Epoch {epoch+1}, MSE = {mse.item():.6f}")

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.3926],
        [0.2201],
        [0.3048]], requires_grad=True)
Epoch 200, MSE = 5.045959
Epoch 400, MSE = 1.453205
Epoch 600, MSE = 0.696129
Epoch 800, MSE = 0.282881
Epoch 1000, MSE = 0.096260
Learned coefficients:
tensor([[1.0070],
        [1.9741],
        [2.5920]], requires_grad=True)


## Bài 10. Giải hệ phương trình bằng Autograd

**Yêu cầu:** Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa 4 phương trình:
A+B=9, C-D=1, A+C=8, B-D=2.
Kiểm tra nghiệm. Nhận xét vì sao bài toán có thể có nhiều nghiệm.

**Giải thích:**
- Ý tưởng: thay vì giải hệ phương trình tuyến tính bằng đại số, ta biến bài toán thành **bài toán tối ưu**: định nghĩa sai số `y1, y2, y3, y4` là hiệu giữa vế trái và vế phải của từng phương trình, sau đó tối thiểu hóa tổng bình phương sai số `sqerr = y1²+y2²+y3²+y4²`.
- Nếu tìm được `A, B, C, D` sao cho `sqerr ≈ 0`, nghĩa là cả 4 phương trình gần như được thỏa mãn đồng thời.
- `A, B, C, D` đều được khởi tạo ngẫu nhiên với `requires_grad=True`, dùng optimizer NAdam để cập nhật qua 2000 epoch, tương tự cách huấn luyện mô hình học máy.

In [20]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

# Yêu cầu: kiểm tra nghiệm với 4 phương trình
print("\nKiểm tra:")
print("A+B =", (A+B).item(), "(mục tiêu 9)")
print("C-D =", (C-D).item(), "(mục tiêu 1)")
print("A+C =", (A+C).item(), "(mục tiêu 8)")
print("B-D =", (B-D).item(), "(mục tiêu 2)")

A = tensor(4.6255, requires_grad=True)
B = tensor(4.3745, requires_grad=True)
C = tensor(3.3745, requires_grad=True)
D = tensor(2.3745, requires_grad=True)

Kiểm tra:
A+B = 8.999954223632812 (mục tiêu 9)
C-D = 1.0000088214874268 (mục tiêu 1)
A+C = 7.999967098236084 (mục tiêu 8)
B-D = 1.999995470046997 (mục tiêu 2)


## Bài 11. Tổng hợp các thao tác PyTorch

**Yêu cầu:**
1. Tạo Tensor X có 24 phần tử, reshape thành 4×6, 2×12, 2×3×4.
2. Tạo A, B kích thước 3×4; tính A+B, A*B, A/B, trung bình và độ lệch chuẩn theo cột.
3. Cho y = 2x² + 5x + 3, dùng autograd tính dy/dx tại x=2, kiểm tra thủ công.
4. Thay đa thức Bài 9 bằng y = 2x² - 3x + 5, huấn luyện và cho biết hệ số tìm được.

**Giải thích chung:** Bài này tổng hợp lại 4 kỹ thuật đã học ở các bài trước: tạo/reshape Tensor (Bài 5), phép toán element-wise + thống kê (Bài 6, 7), autograd tính đạo hàm (Bài 8), và Gradient Descent để "học" hệ số đa thức (Bài 9).

In [21]:
import torch

X = torch.arange(24)   # tạo Tensor 24 phần tử: 0,1,...,23
print("X ban đầu:", X)
print("Shape:", X.shape)

X_4x6 = X.reshape(4, 6)
print("\nReshape 4x6:")
print(X_4x6)

X_2x12 = X.reshape(2, 12)
print("\nReshape 2x12:")
print(X_2x12)

X_2x3x4 = X.reshape(2, 3, 4)
print("\nReshape 2x3x4:")
print(X_2x3x4)

X ban đầu: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
Shape: torch.Size([24])

Reshape 4x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2x12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2x3x4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [22]:
A = torch.randn(3, 4)
B = torch.randn(3, 4)
print("A:"); print(A)
print("B:"); print(B)

print("\nA+B:"); print(A + B)
print("\nA*B (element-wise):"); print(A * B)
print("\nA/B:"); print(A / B)

print("\nTrung bình theo cột (dim=0):"); print(torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột (dim=0):"); print(torch.std(A, dim=0))

A:
tensor([[ 0.5748, -0.4024,  1.2993, -0.3958],
        [ 0.0523, -1.1732,  1.7108,  0.4438],
        [ 0.3067, -0.2306,  0.6247, -0.0879]])
B:
tensor([[-1.5055, -1.5974,  0.8867, -1.0242],
        [ 0.8188,  0.2704, -0.6626,  0.7056],
        [ 1.3780, -0.7101,  0.2938, -0.9920]])

A+B:
tensor([[-0.9307, -1.9998,  2.1860, -1.4200],
        [ 0.8711, -0.9027,  1.0482,  1.1494],
        [ 1.6848, -0.9407,  0.9185, -1.0799]])

A*B (element-wise):
tensor([[-0.8654,  0.6428,  1.1521,  0.4054],
        [ 0.0428, -0.3172, -1.1335,  0.3131],
        [ 0.4227,  0.1637,  0.1835,  0.0872]])

A/B:
tensor([[-0.3818,  0.2519,  1.4653,  0.3864],
        [ 0.0639, -4.3385, -2.5821,  0.6289],
        [ 0.2226,  0.3247,  2.1266,  0.0886]])

Trung bình theo cột (dim=0):
tensor([ 0.3113, -0.6020,  1.2116, -0.0133])
Độ lệch chuẩn theo cột (dim=0):
tensor([0.2613, 0.5020, 0.5483, 0.4247])


In [23]:
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)
print("Đạo hàm thủ công 4x+5 tại x=2:", 4 * 2 + 5)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
x.grad = tensor(13.)
Đạo hàm thủ công 4x+5 tại x=2: 13


In [24]:
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([X * X, X, np.ones_like(X)])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)

EPOCHS = 2000   # có thể tăng lên 5000 nếu muốn hội tụ sát hơn nữa
for epoch in range(EPOCHS):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    if (epoch + 1) % 400 == 0:
        print(f"Epoch {epoch+1}, MSE = {mse.item():.6f}")

print("Learned coefficients (target [2, -3, 5]):")
print(w)

Initial coefficients:
tensor([[-0.2926],
        [-2.0184],
        [ 1.1416]], requires_grad=True)
Epoch 400, MSE = 48.971966
Epoch 800, MSE = 1.074204
Epoch 1200, MSE = 0.669138
Epoch 1600, MSE = 0.452757
Epoch 2000, MSE = 0.274104
Learned coefficients (target [2, -3, 5]):
tensor([[ 2.0117],
        [-2.9671],
        [ 4.3097]], requires_grad=True)


# - HẾT -